#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cgts-mtce-compute
Version  : 6a5e10492cf09b47463cd38d806c36386a459718
Release  : 4
URL      : https://github.com/openstack/stx-metal/archive/6a5e10492cf09b47463cd38d806c36386a459718.tar.gz
Source0  : https://github.com/openstack/stx-metal/archive/6a5e10492cf09b47463cd38d806c36386a459718.tar.gz
Summary  : Titanium Cloud Platform Common Node Maintenance Package
Group    : Development/Tools
License  : Apache-2.0
Requires: cgts-mtce-compute-config
Requires: /bin/systemctl
Requires: bash
Requires: qemu-kvm-ev
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : systemd
BuildRequires : systemd-devel
BuildRequires : tox
BuildRequires : virtualenv
Patch1: 0001-add-Makefile-for-cgts-mtce-compute-1.0.patch

%description
agent/client daemons as well as the hardware and process monitor
             daemons, hardware watchdog process, resource and file system daemons
             as well as initialization and support files for each.

%package config
Summary: config components for the cgts-mtce-compute package.
Group: Default

%description config
config components for the cgts-mtce-compute package.


%prep
%setup -q -n stx-metal-6a5e10492cf09b47463cd38d806c36386a459718
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539004635
pushd mtce-compute/cgts-mtce-compute-1.0
make  %{?_smp_mflags} default
popd

%install
export SOURCE_DATE_EPOCH=1539004635
rm -rf %{buildroot}
pushd mtce-compute/cgts-mtce-compute-1.0
echo "Empty"
popd
## install_append content
%global subdir "mtce-compute/cgts-mtce-compute-1.0"
%global SOURCE1 goenabled
%global SOURCE2 e_nova-init
%global SOURCE3 nova-cleanup
%global SOURCE4 nova-startup
%global SOURCE11 nova-cleanup.conf
%global SOURCE12 nova-compute.conf
%global SOURCE14 libvirtd.conf
%global SOURCE21 nova-goenabled.sh
%global SOURCE22 virt-support-goenabled.sh
%global SOURCE31 goenabled-compute.service
%global SOURCE32 e_nova-init.service
%global _sysconfdir '/usr/local/etc'
%global local_etc_pmond      %{_sysconfdir}/pmon.d
%global local_etc_goenabledd %{_sysconfdir}/goenabled.d
%global local_etc_nova       %{_sysconfdir}/nova
%global _unitdir "/usr/lib/systemd/system"
install -m 755 -p -D %{subdir}/scripts/%{SOURCE1} %{buildroot}/%{_sysconfdir}/init.d/goenabledCompute
install -m 755 -p -D %{subdir}/scripts/%{SOURCE2} %{buildroot}/%{_sysconfdir}/init.d/e_nova-init
install -m 755 -p -D %{subdir}/scripts/%{SOURCE3} %{buildroot}/%{_sysconfdir}/init.d/nova-cleanup
install -m 755 -p -D %{subdir}/scripts/%{SOURCE4} %{buildroot}/%{_sysconfdir}/init.d/nova-startup
install -m 755 -d                %{buildroot}%{local_etc_pmond}
install -m 755 -d                %{buildroot}%{local_etc_nova}
install -m 644 -p -D %{subdir}/scripts/%{SOURCE11} %{buildroot}%{local_etc_nova}/nova-cleanup.conf
install -m 644 -p -D %{subdir}/scripts/%{SOURCE12} %{buildroot}%{local_etc_nova}/nova-compute.conf
install -m 644 -p -D %{subdir}/scripts/%{SOURCE14} %{buildroot}%{local_etc_pmond}/libvirtd.conf
install -m 755 -d                %{buildroot}%{local_etc_goenabledd}
install -m 755 -p -D %{subdir}/scripts/%{SOURCE21} %{buildroot}%{local_etc_goenabledd}/nova-goenabled.sh
install -m 755 -p -D %{subdir}/scripts/%{SOURCE22} %{buildroot}%{local_etc_goenabledd}/virt-support-goenabled.sh
install -m 644 -p -D %{subdir}/scripts/%{SOURCE31} %{buildroot}%{_unitdir}/goenabled-compute.service
install -m 644 -p -D %{subdir}/scripts/%{SOURCE32} %{buildroot}%{_unitdir}/e_nova-init.service
%clean
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/goenabled.d/nova-goenabled.sh
/usr/local/etc/goenabled.d/virt-support-goenabled.sh
/usr/local/etc/init.d/e_nova-init
/usr/local/etc/init.d/goenabledCompute
/usr/local/etc/init.d/nova-cleanup
/usr/local/etc/init.d/nova-startup
/usr/local/etc/nova/nova-cleanup.conf
/usr/local/etc/nova/nova-compute.conf
/usr/local/etc/pmon.d/libvirtd.conf

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/e_nova-init.service
/usr/lib/systemd/system/goenabled-compute.service
